### ISSUE TITLE
Adding background-image to app-header ignored

### ISSUE THREAD

**Issue by diddledan** [Polymer/pwa-starter-kit#277]
Please forgive me if this is not specific to PWA Starter Kit. I'm not sure where the problem lies, so I am posting this here to hopefully get some guidance on the correct place to start looking or where else to post the issue.

This is the scenario:

I modified the PWA Starter Kit's `my-app.js` to include some extra styles to add a background image to the header, which I gathered from the `app-header` documentation:
```css
app-header {
    background-color: var(--app-header-background-color);
    color: var(--app-header-text-color);
    border-bottom: 1px solid #eee;
    --app-header-background-front-layer: {
        background-position: center center;
        background-image: url(images/header-bg-1600.jpg);
    };
    --app-header-background-rear-layer: {
        background-color: var(--app-header-background-color);
    };
}
```

The app, however, seemingly ignores these rules. The two variables in the CSS above are not transposed as they should be into the runtime state of the `app-header` via the `@apply` CSS rules. This causes the background image to not display at all because the `app-header` CSS converts it's rules from:

```css
#backgroundFrontLayer {
    @apply --app-header-background-front-layer;
}

#backgroundRearLayer {
    opacity: 0;
    @apply --app-header-background-rear-layer;
}
```

into (at runtime):

```css
#backgroundFrontLayer {
    ;
}

#backgroundRearLayer {
    opacity: 0;
    ;
}
```

My app which shows the problem is at https://isitoutyet.info/. The sourcecode is at https://github.com/bowlhat/isitoutyet. Any guidance would be awesome :-)
