### ISSUE TITLE
Set service-worker.js to Cache-Control: max-age=0?

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit#310]
Should we set `service-worker.js` to `Cache-Control: max-age=0`, right?

Something like this in the `server/app.yml`?

```yml
handlers:
- url: /service-worker\.js
  static_files: service-worker.js
  upload: service-worker\.js
  expiration: 0m
```
